sudo: required
dist: trusty
group: edge
language: python
python:
  - "2.7"
env:
  global:
    - secure: eg6Lo+RHK3gizOAnNjgOuvvlsjCnVhpFsh30udQkXj6OBWywZly2Owj6QHCYhAuVRQfRnWr5UvLgLgqUxn0sTHs+h1t4naYaFHpMEhVpLPL3cItlal0pFBsp8lwY6UAM5uk1HqA1Iyn9NVpDHyAVkfsZjCq4+Bc0xlzGfR6bejjutzLy0nK5aaDU/j2NGdEI7d9DE6OicvCELUFcvryNmSVb1IYrC9QFj9dBDRszTnQT5Pf4O+3LIcQCYdBSIhEL16CDOnOUbO4xnU5Q6UvqKeiy5ZYgYHatKW2ChLVWBDhkXFhDagB6wAI0nizqmLDviB/6RrgpRPMiqP+RnDQD+/GM8yWEXwKgh51bFGcUsQK/A9nQNIaD3UNNMHUDZ6sHgubsHM3OT1sSkjsiuRpBFDhJ0T3IyzgwPv2ndir4Oq/8GHRc5A4MwkBK+PcXEXK0fVUUxIAhXT7WDTNHBhSuPiLTlPYfB9e8v4Y+5kSo9MCgVVb+1MOQVfhPhVZ4gjaivZpvMJyzdKD+q2PNL4/K8ha8Q4Y8ymKeU4it5MfuLS2de/eESOahP+THcXWSKGE+5etZ5fNAkMF40AnBwWHx88JDLlLNY3xwe0M0e7raGKkMwV3cXU7Ea+gz8ZApqaXIttnUj2Q20BkTyOGtRg2GjeZBRNcLcdk5EK/XBWTHzIo= # SNAP_API_AUTH
    - secure: E73S8LZCrN808GyA6tOo8YVhY9DUxEX08lb3Riwx7vrDCvNiCMD/IYnuFH5f0JAtRjZheJDyamq0QZvb0OHl8euhpnL/XyMd2PiKcYNHkBODOsrvq63SAqh6GVVRSHFZdb5HZF7kzfZvpDMpC3pv+uUef3OwSNSeVOf9FaeM0VWvK5U67SXpW+Tln17Yp1hHBjVdP2Qs505dIa5TnLEdQbPJyBrw+7XJbEsXcHKoXgx/nlHhUn3K7EZk8zQnTSYeLdTdh7DblNk9PZVhygiXTFNcRUn6L/6Ioog7Q0Q23+l0H/Sfh8+TGj3pJlrC7xz5srSiDfwup4+GkNH9mL+lSneUbagKLEqEvCY6/5zH3kaqnnZBaBsAFwyD2nozDjMlbWWQ/FaM86rARjdgBOT4mK81xHc1KaJ08NQt9OUg8G737AViY/OsTUorLqpod4edK2dv2z6kDiWg4wBbamouygEy+2nzHbC1F3wOUrxBo5IdB+fdf0zjfp8wZSFlrhjL9vIWay5jpWtFoRYuUH6qtW19XqpEHlIZldrIjYn3p4Ow/L3fYG+vli5kgz6s8AS7AmEHeO1bid0f+OecnE+YBq9irgnReniYAGaDPTcuBemmjcARvhOcU3a7NRvuPCEbqPU41oTxcocdwZa0Dfy97kvgQNsD/aT2qE/kLPxbFjo= # CROWDIN_API_KEY
  matrix:
    - SELENIUM_WEBDRIVER=default
matrix:
  include:
    - python: 2.7.14
      env: SELENIUM_WEBDRIVER=default
  fast_finish: true
stages:
  - name: test
    if: tag IS blank AND (NOT branch = master)
  - name: deploy
    if: branch = master AND (NOT type IN (pull_request))
jobs:
  include:
    - stage: test
      before_install:
        - gem install sass -v 3.3.4
      install:
        - pip install -U setuptools
        - pip install -e .
        - pip install -e git+https://github.com/ocadotechnology/codeforlife-portal.git#egg=codeforlife-portal #TODO: Remove as part of #688
        - pip install crowdin-cli-py
        - pip install coverage
      before_script:
        - wget http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/bin/
        - export CHROME_BIN=chromium-browser
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
      script:
        - coverage run setup.py test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      install:
        - pip install -U setuptools
        - pip install -e .
        - pip install -e git+https://github.com/ocadotechnology/codeforlife-portal.git#egg=codeforlife-portal #TODO: Remove as part of #688
        - python setup.py install
        - pip install crowdin-cli-py
      script:
        - mkdir -p game/locale
        - cd game && django-admin makemessages -l en_GB --no-wrap && cd -
        - cd game && django-admin makemessages -l en_GB --no-wrap -d djangojs --ignore "static/game/js/foundation/*" && cd - # some files from foundation use '_' for their own purpose
        - crowdin-cli-py upload sources
        - ./.crowdin-get-translations
        - git config --global user.name "semantic-release (via TravisCI)"
        - git config --global user.email "semantic-release@travis"
        - pip install python-semantic-release==3.11.2
        - semantic-release publish
      after_success:
        - "curl -d POST -v https://semaphoreci.com/api/v1/projects/${SEMAPHORE_PROJECT_ID}/master/build?auth_token=${SEMAPHORE_API_AUTH}"
